#!/bin/bash
#PBS -N bbbblast
#PBS -l nodes=1:ppn=8
#PBS -l walltime=1:00:00
#PBS -q regular
#PBS -o "quick.out"
#PBS -e "quick.err"

BLASTN="/global/u2/g/glock/apps.carver/blast/bin/blastn"
INPUT="/global/scratch2/sd/glock/blast.input/contigs.fa.100"
OUTPUT_FILE="blastn.out"
OUTPUT_DIR="${PBS_O_WORKDIR-$PWD}"

PROFILE_INTERVAL=30
PROFILE_INTERVAL=5
PROFILE_INTERVAL=1

DB_DIR="/global/scratch2/sd/glock/blast.db"
DBS="nt_dustmasked.00 nt_dustmasked.01 nt_dustmasked.02 nt_dustmasked.03 nt_dustmasked.04 nt_dustmasked.05 nt_dustmasked.06 nt_dustmasked.07 nt_dustmasked.08 nt_dustmasked.09 nt_dustmasked.10 nt_dustmasked.11 nt_dustmasked.12 nt_dustmasked.13"
DBS="nt_dustmasked.00"
DBS="nt_dustmasked.00 nt_dustmasked.01 nt_dustmasked.02 nt_dustmasked.03"

SCRATCH_DEV="/dev/dm-0"
SCRATCH_DIR="/local/tmp/$USER"

THREADS="${PBS_NP-1}"
APWRAP="aprun -n1 -N1 -d $THREADS"  # for running on Cray
APWRAP="strace -T -ttt -o $OUTPUT_DIR/strace.out"                  # when running on cluster
APWRAP=""

PROFILE_OUTPUT_DIR="/global/scratch2/sd/glock/blast-test.profile"

#
#  Ensure we don't carry over the results from a previous profiling run
#
if [ -d $PROFILE_OUTPUT_DIR ]; then
  echo "$(date) - Need to kill $PROFILE_OUTPUT_DIR"
  if [ -d ${PROFILE_OUTPUT_DIR}.old ]; then
    rm -rf ${PROFILE_OUTPUT_DIR}.old
  fi
  mv -v $PROFILE_OUTPUT_DIR ${PROFILE_OUTPUT_DIR}.old
fi
mkdir -p $PROFILE_OUTPUT_DIR

#
#  Functions to generate profiling data
#
drop_begin() {
    echo "PROF_BEGIN $(date +%s)"
}
startmon() { 
    echo "$(date) - Starting IO profile..."
    drop_begin  > $PROFILE_OUTPUT_DIR/prof_iostat.txt
    iostat -dkt $PROFILE_INTERVAL $SCRATCH_DEV >> $PROFILE_OUTPUT_DIR/prof_iostat.txt &

    if [ -e $PROFILE_OUTPUT_DIR/prof_df.txt ]; then
        rm $PROFILE_OUTPUT_DIR/prof_df.txt
    fi
    if [ -e $PROFILE_OUTPUT_DIR/prof_ps.txt ]; then
        rm $PROFILE_OUTPUT_DIR/prof_ps.txt
    fi
    if [ -e $PROFILE_OUTPUT_DIR/prof_filehandles.txt ]; then
        rm $PROFILE_OUTPUT_DIR/prof_filehandles.txt
    fi

    while [ 1 ]
    do 
        # save record of ssd capacity
        drop_begin >> $PROFILE_OUTPUT_DIR/prof_df.txt
        df -k >> $PROFILE_OUTPUT_DIR/prof_df.txt

        # save record of running processes
        drop_begin >> $PROFILE_OUTPUT_DIR/prof_ps.txt
        ps -U $USER -o pid,ppid,lwp,nlwp,etime,pcpu,pmem,rss,vsz,maj_flt,min_flt,cmd -www >> $PROFILE_OUTPUT_DIR/prof_ps.txt

        # save record of open file handles
        drop_begin >> $PROFILE_OUTPUT_DIR/prof_filehandles.txt
        cat /proc/sys/fs/file-nr >> $PROFILE_OUTPUT_DIR/prof_filehandles.txt

        # save record of virtual memory state
        drop_begin >> $PROFILE_OUTPUT_DIR/prof_vmstat.txt
        cat /proc/vmstat >> $PROFILE_OUTPUT_DIR/prof_vmstat.txt

        sleep ${PROFILE_INTERVAL}s

    done
}

#
#  Stage in input data and create database alias file
#
if [ -d "$SCRATCH_DIR" ]; then
  rm -rf $SCRATCH_DIR
fi
mkdir -p $SCRATCH_DIR || exit 1
if [ ! $NO_STAGE ]; then
    echo "$(date) - Staging in $DB_DIR/${dbfile}* ($(du -hcs $DB_DIR/${dbfile}*))"
    for dbfile in $DBS
    do
        cp -v $DB_DIR/${dbfile}* $SCRATCH_DIR/
    done

    echo "$(date) - Creating $SCRATCH_DIR/testdb.nal"
    cat <<EOF > $SCRATCH_DIR/testdb.nal
TITLE nt
DBLIST $DBS
EOF
else
    # Create the alias in the master db directory if we aren't
    # staging data to a local disk
    echo "$(date) - Creating $DB_DIR/testdb.nal"
cat <<EOF > $DB_DIR/testdb.nal
TITLE nt
DBLIST $DBS
EOF

fi

#
#  Start profiling
#
if [ ! $NO_PROFILE ]; then
    startmon &
    monpid=$!
fi

$APWRAP $BLASTN \
    -num_threads $THREADS \
    -evalue 1e-30 \
    -perc_identity 90 \
    -word_size 45 \
    -task megablast \
    -outfmt 0 \
    -query $INPUT \
    -db ${DB_DIR}/testdb > $SCRATCH_DIR/$OUTPUT_FILE 2> $SCRATCH_DIR/${OUTPUT_FILE%out}err

echo "$(date) - Begin moving output data off of local disk"
mv $SCRATCH_DIR/$OUTPUT_FILE $OUTPUT_DIR/
mv $SCRATCH_DIR/${OUTPUT_FILE%out}err $OUTPUT_DIR/
echo "$(date) - Finished moving output data off of local disk"
echo "$(date) - Removing $SCRATCH_DIR"
rm -rf $SCRATCH_DIR
echo "$(date) - Done cleaning up $SCRATCH_DIR"

if [ ! $NO_PROFILE ]; then
    ### Let one last ps/df fire before shutting everything down
    sleep 90
    kill $monpid
fi

echo "Final job status from Torque:"
qstat -f $PBS_JOBID
